### ISSUE TITLE
Outputs not rendering?

### ISSUE THREAD

**Issue by mrisdal** [SocialDataSci/Geospatial_Data_with_Python#1]
I would love to share a link to the notebook, but I'm not seeing any of the output visuals.

**Comment by dreyco676** [comment]
Couple questions: 

By output do you mean the charts and graphs or are you taking about the static images? 

Are you suggesting that I include all of the output of the notebook? I can do that if you'd like. The idea was to make it so the user runs it.

Are are you just sending the .ipynb? If so you need keep the img folder with it.

Or something else?

**Comment by dreyco676** [comment]
I haven't heard anything back, if this is still an issue please reopen.
